# Generated by Django 3.1.1 on 2020-12-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_bids_commet'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(default='', max_length=40),
        ),
    ]
