# Generated by Django 3.1.1 on 2020-12-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
