# Generated by Django 3.1.1 on 2020-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctions_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
