# Generated by Django 3.1.1 on 2020-12-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201221_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='starting_bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='max_bid', to='auctions.bids'),
        ),
    ]
