# Generated by Django 3.1.1 on 2020-12-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201229_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auctions', unique=True),
        ),
    ]
