# Generated by Django 3.1.1 on 2020-12-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='last_bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='starting_bid',
            field=models.IntegerField(),
        ),
    ]
