# Generated by Django 3.1.1 on 2021-01-05 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auctions_user_created_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='user_created_auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
