# Generated by Django 3.1.1 on 2021-01-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210105_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='last_bid',
            field=models.IntegerField(default='There is no bid yet'),
        ),
    ]
