# Generated by Django 3.1.1 on 2021-01-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210105_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='last_bid',
            field=models.IntegerField(default=0),
        ),
    ]
