# Generated by Django 3.1.1 on 2021-01-06 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20210106_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user_who_made_last_successful_bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='user_who_made_last_successful_bid',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
