# Generated by Django 3.1.1 on 2021-01-12 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20210106_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='commet',
            name='auction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
        migrations.AddField(
            model_name='commet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
