# Generated by Django 3.1.1 on 2021-01-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20210112_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commet',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
    ]
